// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvynargpkwhslxmppcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydnluYXJncGt3aHNseG1wcGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzUwMjIsImV4cCI6MjA3MjAxMTAyMn0.L5d1vk_42lFdwPPWJUpDuzxeH-wKJSU5P6HLGSexdbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});